<a href="https://colab.research.google.com/github/jmora420-hue/Ciencia_de_datos/blob/main/ExposicionEjemplo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import warnings
warnings.filterwarnings('ignore')
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Tanques_120.csv")
df.head()

        fecha  nivel_tanque_lineal  crecimiento_polinomico estado_proceso_locf
0  2026-01-01            10.993428                     NaN              Fase A
1  2026-01-02            11.740278               23.306956                 NaN
2  2026-01-03            15.328991               18.623654                 NaN
3  2026-01-04            19.096480               24.244846                 NaN
4  2026-01-05            17.598920               16.935874                 NaN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   fecha                   120 non-null    object
 1   nivel_tanque_lineal     105 non-null    float64
 2   crecimiento_polinomico  89 non-null     float64
 3   estado_proceso_locf     4 non-null      object
dtypes: float64(2), object(2)
memory usage: 3.9+ KB

In [5]:
df.isnull().sum()

fecha                       0
nivel_tanque_lineal        15
crecimiento_polinomico     31
estado_proceso_locf       116
dtype: int64

In [8]:
df['nivel_tanque_lineal'] = df['nivel_tanque_lineal'].interpolate(method='linear')
df.head(20)

,fecha,nivel_tanque_lineal,crecimiento_polinomico,estado_proceso_locf
0,2026-01-01,10.993428,NaN,Fase A
1,2026-01-02,11.740278,23.306956,NaN
2,2026-01-03,15.328991,18.623654,NaN
3,2026-01-04,19.096480,24.244846,NaN
4,2026-01-05,17.598920,16.935874,NaN
5,2026-01-06,19.615760,12.580915,NaN
6,2026-01-07,22.634138,14.563017,NaN
7,2026-01-08,25.652517,22.859371,NaN
8,2026-01-09,25.195505,34.773293,NaN
9,2026-01-10,29.236381,34.147501,NaN
10,2026-01-11,30.244898,21.710036,NaN
11,2026-01-12,31.253414,17.986421,NaN
12,2026-01-13,34.685605,26.397577,NaN
13,2026-01-14,34.735532,33.894753,NaN
14,2026-01-15,34.785458,30.121400,NaN
15,2026-01-16,39.127526,31.230723,NaN
16,2026-01-17,40.243245,37.878699,NaN
17,2026-01-18,44.914209,37.847989,NaN
18,2026-01-19,44.486473,32.548167,NaN
19,2026-01-20,45.494720,39.132293,NaN

In [9]:
df['crecimiento_polinomico'] = df['crecimiento_polinomico'].interpolate(method='polynomial', order=2)
df.head(20)

,fecha,nivel_tanque_lineal,crecimiento_polinomico,estado_proceso_locf
0,2026-01-01,10.993428,NaN,Fase A
1,2026-01-02,11.740278,23.306956,NaN
2,2026-01-03,15.328991,18.623654,NaN
3,2026-01-04,19.096480,24.244846,NaN
4,2026-01-05,17.598920,16.935874,NaN
5,2026-01-06,19.615760,12.580915,NaN
6,2026-01-07,22.634138,14.563017,NaN
7,2026-01-08,25.652517,22.859371,NaN
8,2026-01-09,25.195505,34.773293,NaN
9,2026-01-10,29.236381,34.147501,NaN
10,2026-01-11,30.244898,21.710036,NaN
11,2026-01-12,31.253414,17.986421,NaN
12,2026-01-13,34.685605,26.397577,NaN
13,2026-01-14,34.735532,33.894753,NaN
14,2026-01-15,34.785458,30.121400,NaN
15,2026-01-16,39.127526,31.230723,NaN
16,2026-01-17,40.243245,37.878699,NaN
17,2026-01-18,44.914209,37.847989,NaN
18,2026-01-19,44.486473,32.548167,NaN
19,2026-01-20,45.494720,39.132293,NaN

In [10]:
df['estado_proceso_locf'] = df['estado_proceso_locf'].ffill()
df.head(20)

,fecha,nivel_tanque_lineal,crecimiento_polinomico,estado_proceso_locf
0,2026-01-01,10.993428,NaN,Fase A
1,2026-01-02,11.740278,23.306956,Fase A
2,2026-01-03,15.328991,18.623654,Fase A
3,2026-01-04,19.096480,24.244846,Fase A
4,2026-01-05,17.598920,16.935874,Fase A
5,2026-01-06,19.615760,12.580915,Fase A
6,2026-01-07,22.634138,14.563017,Fase A
7,2026-01-08,25.652517,22.859371,Fase A
8,2026-01-09,25.195505,34.773293,Fase A
9,2026-01-10,29.236381,34.147501,Fase A
10,2026-01-11,30.244898,21.710036,Fase A
11,2026-01-12,31.253414,17.986421,Fase A
12,2026-01-13,34.685605,26.397577,Fase A
13,2026-01-14,34.735532,33.894753,Fase A
14,2026-01-15,34.785458,30.121400,Fase A
15,2026-01-16,39.127526,31.230723,Fase A
16,2026-01-17,40.243245,37.878699,Fase A
17,2026-01-18,44.914209,37.847989,Fase A
18,2026-01-19,44.486473,32.548167,Fase A
19,2026-01-20,45.494720,39.132293,Fase A

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   fecha                   120 non-null    object
 1   nivel_tanque_lineal     120 non-null    float64
 2   crecimiento_polinomico  119 non-null    float64
 3   estado_proceso_locf     120 non-null    object
dtypes: float64(2), object(2)
memory usage: 3.9+ KB